version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_v:/var/www/html
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      - inception 
    ports: 
      - "3306:3306"
    volumes:
      - mariadb_v:/var/lib/mysql

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: ./Dockerfile
    ports:
      - "6379:6379"
    networks:
      - inception
    
  ftp_server:
    container_name: ftp_server
    build:
      context: ./requirements/bonus/ftp_server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "21:21"
    networks:
      - inception
    volumes:
      - wordpress_v:/var/wordpress
    depends_on:
      - wordpress
    
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: ./Dockerfile 
    networks:
      - inception
    ports:
      - "4242:80"
    
  cadvisor:
    container_name: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: ./Dockerfile
    networks:
      - inception
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro  

  website:
    container_name: website
    build:
      context: ./requirements/bonus/website
      dockerfile: ./Dockerfile
    networks:
      - inception
    ports:
      - "3000:3000"
networks:
  inception:

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hrings/data/mariadb
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hrings/data/wordpress