version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: ./Dockerfile
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_v:/var/www/html
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      - inception 
    ports: 
      - 3306:3306
    volumes:
      - mariadb_v:/var/lib/mysql
networks:
  inception:

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mariadb_v
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/wordpress_v