languageCode = "en-us"
title = "Inception"

[permalinks]
  pages = "/:filename/"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Pages"
    pre = "edit"
    url = "/pages/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"